/**
 * Publisher
 *
 * Stores the synopsis in KV (for history and dedup) and
 * creates a GitHub Issue so the team can read, comment, and react.
 */

import type { Synopsis } from "./synthesizer";
import type { AgentOutput } from "./agents";

export interface PublishResult {
  kvKey: string;
  issueUrl?: string;
  issueNumber?: number;
  alreadyPublished: boolean;
}

/**
 * Publish the synopsis to KV + GitHub Issues.
 * Deduplicates by date — won't create a second issue for the same week.
 */
export async function publish(
  synopsis: Synopsis,
  agentOutputs: AgentOutput[],
  env: AdvisorEnv
): Promise<PublishResult> {
  const kvKey = `synopsis:${synopsis.date}`;

  // Dedup check — don't publish twice for the same date
  const existing = await env.ADVISOR_KV.get(kvKey);
  if (existing) {
    return { kvKey, alreadyPublished: true };
  }

  // Build the full GitHub Issue body
  const issueBody = buildIssueBody(synopsis, agentOutputs);

  // Create GitHub Issue
  const issueResult = await createGitHubIssue(
    env.GITHUB_REPO,
    env.GITHUB_TOKEN,
    `Weekly Strategic Brief — ${synopsis.date} (W${synopsis.weekNumber})`,
    issueBody,
    [env.GITHUB_ISSUE_LABEL ?? "advisor"]
  );

  // Store in KV (TTL: 1 year)
  await env.ADVISOR_KV.put(kvKey, JSON.stringify({
    synopsis,
    issueUrl: issueResult.url,
    issueNumber: issueResult.number,
    publishedAt: new Date().toISOString(),
  }), { expirationTtl: 60 * 60 * 24 * 365 });

  return {
    kvKey,
    issueUrl: issueResult.url,
    issueNumber: issueResult.number,
    alreadyPublished: false,
  };
}

// ─── Issue body builder ───────────────────────────────────────────────────────

function buildIssueBody(synopsis: Synopsis, agentOutputs: AgentOutput[]): string {
  const successfulAgents = agentOutputs.filter((a) => !a.error);
  const failedAgents = agentOutputs.filter((a) => a.error);

  const sections: string[] = [
    `> 🤖 Auto-generated by Kill Switch Advisor · ${synopsis.date} · Week ${synopsis.weekNumber}`,
    `> Synthesized from ${successfulAgents.length} advisor agents${failedAgents.length > 0 ? ` (${failedAgents.length} failed: ${failedAgents.map((a) => a.name).join(", ")})` : ""}`,
    "",
    "---",
    "",
    synopsis.markdown,
    "",
    "---",
    "",
    "## 📋 Raw Agent Reports",
    "",
    "<details>",
    "<summary>Click to expand full advisor reports</summary>",
    "",
  ];

  for (const agent of agentOutputs) {
    sections.push(`### ${agent.name} Agent — ${agent.role}`);
    if (agent.error) {
      sections.push(`_Failed: ${agent.error}_`);
    } else {
      sections.push(agent.content);
    }
    sections.push("");
  }

  sections.push("</details>");
  sections.push("");
  sections.push("---");
  sections.push("_To adjust advisor behavior, edit `packages/advisor/src/agents.ts`._");
  sections.push("_To change schedule, edit `packages/advisor/wrangler.toml` crons._");

  return sections.join("\n");
}

// ─── GitHub API ───────────────────────────────────────────────────────────────

async function createGitHubIssue(
  repo: string,
  token: string,
  title: string,
  body: string,
  labels: string[]
): Promise<{ url: string; number: number }> {
  const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "kill-switch-advisor/1.0",
    },
    body: JSON.stringify({ title, body, labels }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`GitHub API error ${response.status}: ${err}`);
  }

  const data = (await response.json()) as { html_url: string; number: number };
  return { url: data.html_url, number: data.number };
}

// ─── Env type ─────────────────────────────────────────────────────────────────

export interface AdvisorEnv {
  ANTHROPIC_API_KEY: string;
  GITHUB_TOKEN: string;
  GITHUB_REPO: string;
  GITHUB_ISSUE_LABEL?: string;
  AGENT_MODEL: string;
  SYNTH_MODEL: string;
  ADVISOR_KV: KVNamespace;
}
